boorsiSho/boorsiSho/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('show/', include('mainPage.urls')),
    path('', include('searchPage.urls')),
    path('fill/', include('fillData.urls')),
]

urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

boorsiSho/fillData/urls.py
app_name = "fillData"

from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.fillInDatabase, name='fillInDatabase'),
]

boorsiSho/mainPage/urls.py
app_name = "mainPage"

from django.urls import path

from . import views

urlpatterns = [
    path('<int:companyId>/',views.showName, name='showName'),
    path('', views.showAll, name='showAll'),
]

boorsiSho/searchPage/urls.py
app_name = "searchPage"

from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.search, name='getSearchQuery'),
]

boorsiSho/mainPage/models.py
from django.db import models

# Create your models here.

class Industry(models.Model):
    name = models.CharField( max_length=100, default="" )

    def __str__(self):
        return str(self.name)
    
class FinancialYear(models.Model):
    year = models.IntegerField( null=True )

    def __str__(self):
        return str(self.year)

class Category(models.Model):
    name = models.CharField( max_length=100, default="" )
    industry = models.ForeignKey( Industry, on_delete=models.CASCADE, null=True )

    def __str__(self):
        return str(self.name)

class Company(models.Model):
    name = models.CharField( max_length=100, default="" )
    symbol = models.CharField( max_length=100, default="" )
    category = models.ForeignKey( Category, on_delete=models.CASCADE, null=True )
    industry = models.ForeignKey( Industry, on_delete=models.CASCADE, null=True )

    def __str__(self):
        return str(self.name)

class FinancialRatio(models.Model):
    currentRatio = models.IntegerField( null=True )
    quickRatio = models.IntegerField( null=True )
    company = models.ForeignKey( Company, on_delete=models.CASCADE, null=True )
    financialYear = models.ForeignKey( FinancialYear, on_delete=models.CASCADE, null=True )

    dateCreated = models.DateTimeField( auto_now_add=True )

    def __str__(self):
        return str(self.company)

boorsiSho/searchPage/models.py
from django.db import models

# Create your models here.

boorsiSho/fillData/views.py
from django.shortcuts import render
from .readFromDatabase import Import
import django_excel as DE

# Create your views here.

def fillInDatabase(request):
    if request.method == 'POST' and request.FILES[ 'dataSheet' ]:
        Import.fillInDatabase( request.FILES[ 'dataSheet' ].get_sheet() )
    return render(request, 'fillData/readData.html')

boorsiSho/mainPage/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Company, FinancialRatio
# Create your views here.

'''def fillInDatabase( request ):
    readFromDatabase.fillInDatabase()
    return HttpResponse("DONE")
   ''' 

def searching(request):
    return render(request,'mainPage/Page1.html')

def showName(request, companyId):
    currentCompany = Company.objects.get( pk=companyId )
    currentFinancialRatio = FinancialRatio.objects.filter( company=currentCompany ).latest( 'dateCreated' )
    return render(request,'mainPage/showName.html', { 'company':currentCompany, 'financialRatio':currentFinancialRatio })

def showAll(request):
    return render(request, 'mainPage/showAll.html', {'allCompanies':Company.objects.all()})

boorsiSho/searchPage/views.py
from django.shortcuts import render
from mainPage.models import Company
from django.http import HttpResponse, JsonResponse

# Create your views here.

'''def search( request ):
    if request.method == 'POST':
        searchKeyWord = request.POST['searchKeyWord']
        companyList = Company.objects.filter( name__icontains=searchKeyWord )
        return render( request, 'searchPage/showSearchResult.html', { 'companyList':companyList } )
    else:
        return render( request, 'searchPage/getSearchQuery.html' )
'''

def search( request ):
    if request.method == 'POST' and request.is_ajax():
        searchKeyWord = request.POST[ 'searchKeyWord' ]
        companyList = Company.objects.filter( name__icontains=searchKeyWord )
        return JsonResponse( {'companyList':companyList} )

boorsiSho/fillData/templates/fillData/readData.html
<!DOCTYPE html>

<html>
    <h1>upload data</h1>
    <form action="{% url 'fillData:fillInDatabase' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <input type="file" name="dataSheet">
        <button type="submit">upload</button>
    </form>    
</html>

boorsiSho/mainPage/templates/mainPage/Page1.html
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="author" content="colorlib.com">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500" rel="stylesheet" />
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" rel="stylesheet"/>
    <link href="css/main.css" rel="stylesheet" />
  </head>
  <body>
    <div class="s002">
      <form>
        <fieldset>
          <legend>سامانه تحلیل بنیادین سهام</legend>
        </fieldset>
        <div class="inner-form">
          <div class="input-field first-wrap">
            <div class="icon-wrap">
				<i class="fa fa-search"></i>
            </div>
            <input class="customInput" type="text" placeholder="نام شرکت یا نماد را وارد کنید."  />
          </div>
          <!--<div class="input-field second-wrap">
             <div class="icon-wrap">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path d="M17 12h-5v5h5v-5zM16 1v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2h-1V1h-2zm3 18H5V8h14v11z"></path>
              </svg>
            </div>
          </div>
          <div class="input-field third-wrap">
            <div class="icon-wrap">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path d="M17 12h-5v5h5v-5zM16 1v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2h-1V1h-2zm3 18H5V8h14v11z"></path>
              </svg>
            </div>
          </div>
          <div class="input-field fouth-wrap">
            <div class="icon-wrap">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"></path>
              </svg>
            </div>
          </div>-->
          <div class="input-field fifth-wrap">
            <button class="btn-search" type="button">جستجو</button>
          </div>
        </div>
      </form>
    </div>
    <script src="js/extention/choices.js"></script>
    <script src="js/extention/flatpickr.js"></script>
    <script>
      flatpickr(".datepicker",
      {});

    </script>
    <script>
      const choices = new Choices('[data-trigger]',
      {
        searchEnabled: false,
        itemSelectText: '',
      });

    </script>
  </body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

boorsiSho/mainPage/templates/mainPage/showAll.html
<!DOCTYPE html>
<html>
    <h1>
        همه ی شرکت ها
    </h1>
    {% for company in allCompanies %}
        <a href="{% url 'mainPage:showName' companyId=company.pk %}">{{company.name}}</a><br>
    {% endfor %}
</html>

boorsiSho/mainPage/templates/mainPage/showName.html
<!DOCTYPE html>
<html lang="en">
<head>
		<title> Page 2 </title>
		<meta charset="utf-8">

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	<style>
	*{
		direction: rtl;
	}
	.rtlDir{
		direction: rtl;
	}
	</style>
	<script>
	$(document).ready(() => {
		$("#NesbatMali").addClass("show");
	});
	</script>
</head>
	<!-- A grey horizontal navbar that becomes vertical on small screens -->
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark rtlDir">
	  <a class="navbar-brand" href="#">سامانه تحلیل بنیادی بورسی‌شو <img src="F:\Documents\IUST\Dr Rasouli Projects\بورسی‌شو\Develope\Frontend\Learning\Pictures\boursiesho-logo.JPG" width="160" height="90" class="d-inline-block align-top" alt="">
    </a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" class="text-warning" href="#"> صفحه اصلی <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">Link</a>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Dropdown
	        </a>
	        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
	          <a class="dropdown-item" href="#">Action</a>
	          <a class="dropdown-item" href="#">Another action</a>
	          <div class="dropdown-divider"></div>
	          <a class="dropdown-item" href="#">Something else here</a>
	        </div>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
	      </li>
	    </ul>
	    <form class="form-inline my-2 my-lg-0">
	      <input class="form-control mr-sm-2" type="search" placeholder="نماد مورد نظر خود را وارد کنید." aria-label="Search" style="margin-left: 10px; width:330px;">
	      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">جستجو</button>
	    </form>
	  </div>
	</nav>
	<div class="jumbotron" style="direction:rtlDir ">
		<h1 align="center">{{ company.name }}</h1>
		‌<hr style="height:1px;border:none;color:#fee80c;background-color:#fee80c;">
		<ul class="list-group" align="right">
	    <li class="list-group-item">{{company.symbol}}</li>
	    <li class="list-group-item">{{company.industry}}</li>
	    <li class="list-group-item">{{company.category}}</li>
	  </ul>
	</div>
	<ul class="nav nav-tabs" >
		<li class="nav-item">
			<a class="nav-link active"data-toggle="tab" href="#NesbatMali">نسبت‌های مالی</a></li>
		<li class="nav-item">
			<a class="nav-link" data-toggle="tab" href="#TarazName">ترازنامه</a></li>
		<li class="nav-item">
			<a class="nav-link" data-toggle="tab" href="#SoudZian">سود و زیان</a></li>
		<li class="nav-item">
			<a class="nav-link" data-toggle="tab" href="#VojohNaghd">گردش وجوه نقد</a></li>
	</ul>
	<div class="tab-content">
	  <div id="NesbatMali" class="tab-pane fade in active">
			<div id="accordion" id=#NesbatMali align="right">
  				<div class="card">
    				<div class="card-header" id="headingOne">
      					<h5 class="mb-0">
        					<button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          						نسبت‌های نقدینگی
        					</button>
      					</h5>
    				</div>

    				<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
      					<div class="card-body">
						  	<div class="jumbotron" style="direction:rtlDir ">
								<ul class="list-group" align="right">
							    	<li class="list-group-item">	نسبت آنی = {{ financialRatio.currentRatio }}</li>
	    							<li class="list-group-item">	نسبت جاری = {{ financialRatio.quickRatio }}</li>
	    
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="card">
					<div class="card-header" id="headingTwo">
						<h5 class="mb-0">
							<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
								Collapsible Group Item #2
							</button>
						</h5>
					</div>
					<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingThree">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Collapsible Group Item #3
        </button>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
</div>
  	</div>
	 </div>
	  <div id="TarazName" class="tab-pane fade">
	    <h3>Menu 1</h3>
	    <p>Some content in menu 1.</p>
	  </div>
	  <div id="SoudZian" class="tab-pane fade">
	    <h3>Menu 2</h3>
	    <p>Some content in menu 2.</p>
	  </div>
		<div id="VojohNaghd" class="tab-pane fade">
			<h3>Menu 2</h3>
			<p>Some content in menu 2.</p>
		</div>
	</div>
</div>
<a class="btn btn-lg btn-primary" href="/docs/4.3/components/navbar/" role="button" align="center">View navbar docs &raquo;</a>
</html>

boorsiSho/searchPage/templates/searchPage/getSearchQuery.html
<!DOCTYPE html>
<html>

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
    </script>

    <script>
        $("#searchBox").keydown(function() {
            $.post(
                {% url 'searchPage:getSearchQuery'  %},
                { 'searchKeyWord':$("#searchBox").val() },
                function(searchResult){

                });
        });
    </script>
</head>

<body>
    <form action="{% url 'searchPage:getSearchQuery' %}" method="POST">
        {% csrf_token %}
        <input type="search" id="searchBox">
        <input type="submit" value="submit">
    </form>
    <ul id="searchResult">
    </ul>
</body>

</html>

boorsiSho/searchPage/templates/searchPage/getSearchQuery2.html
{% load static %}
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="author" content="colorlib.com">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500" rel="stylesheet" />
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" rel="stylesheet"/>
    <link href="{% static 'searchPage/main.css' %}" rel="stylesheet" />
    <style>
    body{
      background-color:DarkKhaki;
    }
    </style>
  </head>
  <body>
    <div class="s002">
      <form action="{% url 'searchPage:getSearchQuery' %}" method="POST">
        <fieldset>
          <legend>سامانه تحلیل بنیادین سهام</legend>
        </fieldset>
        
        <div class="inner-form">
          
          {% csrf_token %}
          <div class="input-field first-wrap">
            <div class="icon-wrap">
				<i class="fa fa-search"></i>
            </div>
          
            <input name="searchKeyWord" class="customInput" type="text" placeholder="نام شرکت یا نماد را وارد کنید."  />
          </div>
          <!--<div class="input-field second-wrap">
             <div class="icon-wrap">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path d="M17 12h-5v5h5v-5zM16 1v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2h-1V1h-2zm3 18H5V8h14v11z"></path>
              </svg>
            </div>
          </div>
          <div class="input-field third-wrap">
            <div class="icon-wrap">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path d="M17 12h-5v5h5v-5zM16 1v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2h-1V1h-2zm3 18H5V8h14v11z"></path>
              </svg>
            </div>
          </div>
          <div class="input-field fouth-wrap">
            <div class="icon-wrap">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"></path>
              </svg>
            </div>
          </div>-->
          <div class="input-field fifth-wrap">
            <button class="btn-search" type="submit">جستجو</button>
          </div>
        
        </div>
      </form>
    </div>
    <script src="{% static 'searchPage/js/extention/choices.js' %}"></script>
    <script src="{% static 'searchPage/js/extention/flatpickr.js' %}"></script>
    <script>
      flatpickr(".datepicker",
      {});

    </script>
    <script>
      const choices = new Choices('[data-trigger]',
      {
        searchEnabled: false,
        itemSelectText: '',
      });

    </script>
  </body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

boorsiSho/searchPage/templates/searchPage/showSearchResult.html
<!DOCTYPE html>
<html>
    <h1>
        search result
    </h1>
    <p>
        {% for company in companyList %}
            <a href="{% url 'mainPage:showName' companyId=company.pk %} ">{{ company.name }}</a>
        {% endfor %}
    </p>
</html>

boorsiSho/searchPage/templates/searchPage/test.html
<!DOCTYPE html>
<html>
<h1>
    enter search
</h1>
<form action="{% url 'searchPage:getSearchQuery' %}" method="POST">
    {% csrf_token %}

    <input type="text" name="searchKeyWord">
    <input type="submit" value="submit">
</form>

</html>